LOAD_ENGINE_GRAMMAR = 'LOAD_ENGINE_GRAMMAR'
ENGINE_START = 'ENGINE_START'
ENGINE_STOP = 'ENGINE_STOP'
EMULATE_RECOGNITION_EVENT = 'EMULATE_RECOGNITION_EVENT'
STOP_MAIN_PROCESS = 'STOP_MAIN_PROCESS'
PERFORM_COMMANDS = 'PERFORM_COMMANDS'

RELOAD_COMMAND_MODULE_FILES = 'RELOAD_COMMAND_MODULE_FILES'
RELOAD_GRAMMAR = 'RELOAD_GRAMMAR'
GRAMMAR_LOADED = 'GRAMMAR_LOADED' 

LOAD_MODULE_MAP = 'LOAD_MODULE_MAP'

SEND_MESSAGE_TO_ELECTRON = 'SEND_MESSAGE_TO_ELECTRON'