XDOTOOL_KEYMAP = {
    'home': 'Home',
    'tab': 'Tab',
    'esc': 'Escape',
    'escape': 'Escape',
    'enter': 'Return',
    'up': 'Up',
    'right': 'Right',
    'down': 'Down',
    'left': 'Left',
    'end': 'End',
    'del': 'Delete',
    'delete': 'Delete',
    'backspace': 'BackSpace',
    'back': 'BackSpace',
    'pageup': 'Page_Up',
    'page_up': 'Page_Up',
    'pagedown': 'Page_Down',
    'page_down': 'Page_Down',
    '\\': 'backslash',
    '[': 'bracketleft',
    ']': 'bracketright',
    'f1': 'F1',
    'f2': 'F2',
    'f3': 'F3',
    'f4': 'F4',
    'f5': 'F5',
    'f6': 'F6',
    'f7': 'F7',
    'f8': 'F8',
    'f9': 'F9',
    'f10': 'F10',
    'f11': 'F11',
    'f12': 'F12',
    
}
