XDOTOOL_KEYMAP = {
    'home': 'Home',
    'tab': 'Tab',
    'esc': 'Escape',
    'escape': 'Escape',
    'enter': 'Return',
    'up': 'Up',
    'right': 'Right',
    'down': 'Down',
    'left': 'Left',
    'end': 'End',
    'del': 'Delete',
    'delete': 'Delete',
    'backspace': 'BackSpace',
    'back': 'BackSpace',
    'pageup': 'Page_Up',
    'page_up': 'Page_Up',
    'pagedown': 'Page_Down',
    'page_down': 'Page_Down',
    '\\': 'backslash',
    '[': 'bracketleft',
    ']': 'bracketright',
}
